<?php

namespace Anexa\CooperadoraBundle\Repository;

/**
 * ConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionRepository extends \Doctrine\ORM\EntityRepository
{
}
